### ISSUE TITLE
Issue running developer examples

### ISSUE THREAD

**Issue by jonmseaman** [realwear/Developer-Examples#1]
I am using Nexus 5X dev device with the RealWear HDK 1.1.2

When I run the developer example app, I cannot get the dictation to work.

Is there something I need too install with the developer example to get them to run?

Here is the error from logcat:
```
11-06 12:04:38.723 11911-11911/com.realwear.hmt1developerexamples D/AndroidRuntime: Shutting down VM
11-06 12:04:38.725 11911-11911/com.realwear.hmt1developerexamples E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.realwear.hmt1developerexamples, PID: 11911
                                                                                    java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                        at android.view.View$DeclaredOnClickListener.onClick(View.java:4458)
                                                                                        at android.view.View.performClick(View.java:5204)
                                                                                        at android.view.View$PerformClick.run(View.java:21155)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
                                                                                        at android.view.View.performClick(View.java:5204) 
                                                                                        at android.view.View$PerformClick.run(View.java:21155) 
                                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.realwear.keyboard.intent.action.DICTATION }
                                                                                        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
                                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                                        at com.realwear.hmt1developerexamples.DictationActivity.onLaunchDictation(DictationActivity.java:56)
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at android.view.View$DeclaredOnClickListener.onClick(View.java:4453) 
                                                                                        at android.view.View.performClick(View.java:5204) 
                                                                                        at android.view.View$PerformClick.run(View.java:21155) 
                                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by lukerealwear** [comment]
Thank you for getting in touch,

Unfortunately the HDK is no longer supported. All pioneer developers that received a HDK should have now have received the HMT to continue development on. If this is not the case please contact support at support@realwear.com

Kind Regards
